import { defineConfig } from "vitest/config"

export default defineConfig({
  test: {
    include: ["**/*.test.ts"],
    setupFiles: ["./db/testSetup.ts"],
    env: {
      SEARXNG_URL: "http://localhost:8090/",
      SEARXNG_MIN_INTERVAL_MS: "0",
      SERPER_API_KEY: "test-key",
      DEEPSEEK_API_KEY: "test-key",
      LLM_PROVIDER: "deepseek",
      LLM_MODEL_NAME: "deepseek-v4-flash",
      RESEARCH_JOB_CREATION_WINDOW_MS: "86400000",
      RESEARCH_MAX_ROOT_JOB_CREATIONS_PER_WINDOW: "100",
      DEEP_SEARCH_MAX_ROOT_JOB_CREATIONS_PER_WINDOW: "20",
      IDEA_JOB_MAX_ROOT_JOB_CREATIONS_PER_WINDOW: "20",
      DEBATE_MAX_ROOT_JOB_CREATIONS_PER_WINDOW: "20",
      DEEP_SEARCH_MAX_SEARCHES: "10",
      DEEP_SEARCH_MAX_RESULTS_PER_SEARCH: "10",
      DEEP_SEARCH_MAX_SELECTED_URLS_PER_ROUND: "30",
      DEEP_SEARCH_MAX_ROUNDS: "3",
      RESEARCH_MAX_SELECTED_PAGES_PER_ROOT_JOB: "400",
      IDEA_JOB_MAX_IDEA_COUNT: "20",
      IDEA_JOB_MAX_DEEP_SEARCH_COUNT: "10",
      DEBATE_MAX_IDEA_COUNT: "12",
      DEBATE_MAX_INITIAL_DEEP_SEARCH_COUNT: "5",
      DEBATE_MAX_SEARCHES_PER_CHILD: "10",
      DEBATE_MAX_RESULTS_PER_SEARCH: "10",
      DEBATE_MAX_RESEARCH_ROUNDS_PER_CHILD: "3",
      DEBATE_MAX_SELECTED_PAGES_PER_JOB: "400",
      SCRAPINGANT_API_KEY: "test-key",
      DATABASE_URL: ":memory:",
      NODE_ENV: "test",
      BETTER_AUTH_URL: "http://localhost:5173",
      BETTER_AUTH_SECRET: "test-secret-that-is-at-least-thirty-two-characters",
      GITHUB_CLIENT_ID: "test-github-client-id",
      GITHUB_CLIENT_SECRET: "test-github-client-secret",
      AUTH_DEBUG_USER_ENABLED: "true",
      AUTH_DEBUG_USER_PASSWORD: "test-debug-password",
    },
  },
})
